### PR TITLE
update to version 18.1.0

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by stuertz** [comment]
Thank you!

**Comment by sannykr** [comment]
@stuertz: I can't see python 27 and 36 builds for windows on anaconda.org, so I will make another pull request with increased build number.

**Comment by stuertz** [comment]
Agreed. The py27 and py36 builds for win32 and win64 failed.
Details can be seen at https://ci.appveyor.com/project/conda-forge/argon2-cffi-feedstock/build/1.0.9

I think upgrading the version number only, to force a new build won't help in that case.
Maybe we have to rerender with the latest smithy? 
I'll have to look deeper into that..

**Comment by stuertz** [comment]
Looks like https://github.com/conda/conda/issues/6527
which is fixed here: https://github.com/isuruf/conda-smithy/commit/f292a04f5c123c3c6c649f97e96d1edfaa7b4639

So rerendering with smithy 2.4.5 AND updating the version number should do the job.

**Pull request merged**
